SECRET_KEY = 'you-will-never-guess'
DEBUG = True
MONGODB_DB = 'flaskbook'
HOSTNAME = 'https://flask-book-porcos2107.c9users.io'
UPLOAD_FOLDER = '/home/ubuntu/workspace/flaskbook/static/images'
STATIC_IMAGE_URL = 'images'
AWS_BUCKET = 'flaskbookso'
AWS_CONTENT_URL = '	https://s3-us-west-2.amazonaws.com'
AWS_SEND_MAIL = False